cmake_minimum_required(VERSION 3.20)
project(voiraig VERSION 1.0.0)
set(CMAKE_CXX_STANDARD 23)
file(GLOB headers CONFIGURE_DEPENDS src/*.hpp)
file(GLOB sources CONFIGURE_DEPENDS src/*.cpp)

option(LOG "Enable Logging" OFF)
option(CHECK "Setup checking and fuzzing" OFF)
option(ASAN "Build with address sanitizer" OFF)
option(LTO "Enable Link-Time Optimization" ON)
option(STATIC "Build static binary" OFF)
include(util.cmake)
include(deps/aiger/aiger_lib.cmake)
include(deps/cadical/cadical_lib.cmake)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(LOG ON CACHE BOOL "Enable Logging" FORCE)
endif()
set(CMAKE_CXX_FLAGS_FUZZING "-O3" CACHE STRING "Flags for fuzzing build type" FORCE)
if(LOG)
  add_compile_definitions("LOG")
endif(LOG)
if(CHECK)
  include(deps/certifaiger/certifaiger_bin.cmake)
endif(CHECK)
add_executable(${PROJECT_NAME} ${sources})
target_compile_options(${PROJECT_NAME} PRIVATE -DGITID="${GIT_ID}")
target_compile_options(${PROJECT_NAME} PRIVATE -DVERSION="${PROJECT_VERSION}")
install(TARGETS ${PROJECT_NAME})

if(STATIC)
  set(BUILD_SHARED_LIBS OFF)
  set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "-static")
endif()

target_link_libraries(voiraig aiger)
target_link_libraries(voiraig cadical_lib)
