#include "backward.hpp"

#include "utils.hpp"

bool backward(aiger *model, std::vector<std::vector<unsigned>> &cex) {
  L1 << "backward";

  // TODO Implement the following algorithm. Look at the codebase to figure out how to do things. I want you to implement a function that takes model and a value of k. Then it encodes an unrolling of deth k for cadical. It enforces that all states are good, except the last which is bad. Then it solves it. When unsat it has prooven safety and needs to build a witness. Otherwise it has a sequence of states. if any of them is a reset state (you need to encode that check for each of them in the circuit) than a violation is found. Don't worry about generating a counterexample at the moment. what i want you to implement are the following sparsification features which have a Boolean option (options.hpp). flipping: use the flippalbe feature of cadical to iterate over the first state. If flippable turn the value to X. For that use the ternary state representation from the start. Then use the existing ternary simulation facilities to simulate one step. for those not already set to X try flipping in the next and so on. if in debug assert that the state is still bad and bad is not X. simulation: set a literal in the first state to X and simulate to the end of the state sequence. if bad is still X continue to the next. otherwise undo and continue to the next. After testing each once go to the next state. keep track of which latches have been set to X before by simulation from previous states, for the rest try in the same way. print some statistics about what and how often this worked. With this sparsified trace I now want you to strengthen the property, i.e., make more states bad. Every sparcified state (i.e., cube) needs to go to every copy of the property. We want to encode: these states (that can reach bad) are also bad. For the majority that is easy since we can just add a clause to the solver that says "not in this cube" for the last one I want to make use of the constraint feature in cadical. So before we had constraint = bad and now we have constraint = bad v cube1 v cube 2 and so on. The constraint will grow quite quickly.
  
}
